package com.example.demo.mapper;

import com.example.demo.domain.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Mar 06 11:50:14 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Mar 06 11:50:14 GMT+08:00 2020
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Mar 06 11:50:14 GMT+08:00 2020
     */
    UserInfo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Mar 06 11:50:14 GMT+08:00 2020
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Mar 06 11:50:14 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserInfo record);


    @Select("select * from user_info where user_name = #{userName} and password = #{password}")
    UserInfo selectByUserNameAndPassword(@Param("userName") String userName,@Param("password") String password);
}